- hosts: web
  tasks:
   - name: copy a file
     copy:
       src: index.html
       dest: /var/www/html
     notify: restart
  handlers:
     - name: restart
       service:
        name: apache2
        state: restarted
