- hosts: web
  tasks:      
   - name: install apache
     apt:
       name: apache2
       state: present
       update_cache: true      
   - name: service check
     service: 
      name: apache2
      state: started
   - name: copy a file
     copy:
      src: index.html
      dest: /var/www/html/      
